version: '3'
services:
  web:
    build: .
    ports:
      - "8888:8888"
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 050705
      MYSQL_DATABASE: music
      MYSQL_USER: root
      MYSQL_PASSWORD: 050705